### ISSUE TITLE
poem.parse() not working

### ISSUE THREAD

**Issue by sewonp18** [quadrismegistus/litlab-poetry#1]
Hello!

We're trying to implement litlab into our project but are having problems with poem.parse(), even though we followed everything in the documentation specified in the README. 

The error message is:

```
>> gen 20181113-0017.52 from TXT...
        >> done.
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    poem.parse()
  File "/Users/sewonpark/Desktop/litlab-poetry/pypoesy.py", line 621, in parse
    for _i,(li,line) in enumerate(self.prosodic.items()):
  File "/Users/sewonpark/Desktop/litlab-poetry/pypoesy.py", line 825, in prosodic
    import prosodic as p
  File "/Users/sewonpark/Desktop/litlab-poetry/prosodic/__init__.py", line 31, in <module>
    dict[lng]=loadDict(lng)
  File "/Users/sewonpark/Desktop/litlab-poetry/prosodic/lib/tools.py", line 230, in loadDict
    return get_class('Dictionary.Dictionary')(lang)
  File "/Users/sewonpark/Desktop/litlab-poetry/prosodic/lib/Dictionary.py", line 61, in __init__
    self.getprep=get_class(self.language+'.get')
  File "/Users/sewonpark/Desktop/litlab-poetry/prosodic/lib/tools.py", line 237, in get_class
    m = getattr(m, comp)
AttributeError: 'module' object has no attribute 'get'
```

<img width="737" alt="screen shot 2018-11-13 at 12 18 13 am" src="https://user-images.githubusercontent.com/20647894/48392485-a37d7500-e6d9-11e8-8188-eb685942ed66.png">

**Comment by quadrismegistus** [comment]
hi Sewon, the quick fix is to remove dicts/fi from the code (if you don’t need finnish parsing). i will work on finding another solution.

peace,
Ryan

**Comment by sewonp18** [comment]
Hey Ryan,

We deleted the folder dicts/fi but am getting this message now -- any chance you know what's happening? Should I have altered lines of code from that folder instead?

Thanks so much again!

peace,
Sewon

<img width="786" alt="screen shot 2018-11-13 at 2 33 32 am" src="https://user-images.githubusercontent.com/20647894/48397817-fb71a700-e6ec-11e8-973f-d02c1052a7b5.png">

**Comment by quadrismegistus** [comment]
hm you deleted dicts/fi folder entirely? my only other guess is to look in lib/Dictionary.py and see if you can comment out the finnish dictionary option. or is it in dicts? i am on the road but will arrive at the airport soon and will look into it then

peace,
Ryan

**Comment by quadrismegistus** [comment]
Hi Sewon, I can't figure out how to push these changes to github since I downloaded the repo as a zip, but here is a new zip from my dropbox that fixes the problem as well as some other changes (to the meter, too: I changed some things in prosodic/config.txt, which you can change back if you like)

https://www.dropbox.com/s/ydqrcjwh7e6zcwc/litlab-poetry-master-2018-11-13.zip?dl=0

Or if you prefer to make the central change yourself, you can do this in prosodic/__init__.py: change the ##load defaults section starting on line 28 to this: (add the exception)

## load defaults
dict={}
for lng in languages:
try:
dict[lng]=loadDict(lng)
except AttributeError:
pass
del lng


Hope this helps!

peace,
Ryan

**Comment by quadrismegistus** [comment]
btw the fix i made left in dicts/fi. not sure if that matters but if you still get the second error with the patched version then i would try putting dicts/fi back in.

sorry for all the mess! i really need to clean all this up. glad you’re using it though! :)

peace,
Ryan

**Comment by sewonp18** [comment]
Hey Ryan @quadrismegistus, 

Thanks so much! It seems to work now when we have a file like test.py in the same directory as the repo. However, when we make a file outside of the litlab repo folder and try to access it as a module (we added a blank __init__.py file inside the repo directory), and do this 


```
from litlab import pypoesy

poem = pypoesy.PoemTXT("""Who will go drive with Fergus now,
And pierce the deep wood's woven shade,
And dance upon the level shore?
Young man, lift up your russet brow,
And lift your tender eyelids, maid,
And brood on hopes and fear no more.

And no more turn aside and brood
Upon love's bitter mystery;
For Fergus rules the brazen cars,
And rules the shadows of the wood,
And the white breast of the dim sea
And all dishevelled wandering stars.""")

poem.parse()

for lineid,lineObj in sorted(poem.prosodic.items()):
  print lineid,lineObj.parse_str()
```

 We keep getting this error 


```
joshseides@Joshs-MacBook-Pro-4 ~/Desktop $ python test.py 
>> gen 20181113-1302.16 from TXT...
>> done.
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    poem.parse()
  File "/Users/joshseides/Desktop/litlab/pypoesy.py", line 621, in parse
    for _i,(li,line) in enumerate(self.prosodic.items()):
  File "/Users/joshseides/Desktop/litlab/pypoesy.py", line 825, in prosodic
    import prosodic as p
  File "/Users/joshseides/Desktop/litlab/prosodic/__init__.py", line 32, in <module>
    dict[lng]=loadDict(lng)
  File "/Users/joshseides/Desktop/litlab/prosodic/lib/tools.py", line 230, in loadDict
    return get_class('Dictionary.Dictionary')(lang)
  File "/Users/joshseides/Desktop/litlab/prosodic/lib/Dictionary.py", line 20, in __init__
    import prosodic
ImportError: No module named prosodic
```

We are really new to python so not sure about how accessing modules like this works but seems to be a really small problem. Wondering if you knew how to address this. Thanks so much again for answering all our questions!

**Comment by quadrismegistus** [comment]
hi Sewon, ya, I haven't set it up very well to run outside of the current working directory.

but! i just made a big cleaning effort on the code and moved it over to a second repository, since it's different enough: https://github.com/quadrismegistus/poetix

this time it should be easy as installing via pip:

pip install poetix

let me know if that works. if you install espeak, too, no need for openmary, and no need for running a server. also the summary() feature may be useful. hope this all helps!

peace,
Ryan
